name = "aafu"
license = "MIT"
licenselink = "https://github.com/ameyer/aafu/blob/master/LICENSE"
description = "Portfolio and blog theme with search and dark/light theme."
homepage = "https://github.com/ameyer/aafu"
demosite = "https://aafu.pages.dev/"
tags = ["portfolio", "accordion", "resume", "blog", "tailwind"]
features = ["responsive", "dark", "clean"]
min_version = "0.134.3"
theme_version = "2025.07.03"

[author]
  name = "Darshan Baral"
  homepage = "https://www.darshanbaral.com/"
